# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-19 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friend_friend',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user_friend',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='friends_app.User'),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
