# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0003_auto_20180220_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friend_friend',
        ),
        migrations.AddField(
            model_name='friendship',
            name='friend_friend',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='friendfriends', to='friends_app.User'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user_friend',
        ),
        migrations.AddField(
            model_name='friendship',
            name='user_friend',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='userfriends', to='friends_app.User'),
            preserve_default=False,
        ),
    ]
